Real-Dev-Squad/discord-slash-commands

src/constants/commands.ts
src/constants/urls.ts

This PR adds the required constants to the Repository

Add constants for URLs and commands

---

package.json

Add a script test to pre-commit so that tests run before committing any changes.

Pre-Commit test

---

.github/workflows/register-commands-staging.yaml
.gitignore
package-lock.json
package.json
src/register.ts
src/typeDefinitions/register.types.d.ts
src/utils/fetch.ts
src/utils/registerCommands.ts

Discord provides us with an endpoint to register all our commands to our bots.
The register.ts file runs on our pipeline and hist that endpoint with all the commands that we want to register.
Created a few files to register all the commands given in commands.ts to the bot.
Added a pipeline to deploy code to register the commands and deploy code to the Cloudflare workers for the staging environment.
For this pipeline to work we must set up the environment variables in the GitHub environment.

Register the commands and deploy the code on CFW

---

.github/workflows/register-commands-staging.yaml

change variable BOT_TOKEN to DISCORD_TOKEN to match the ENVIRONMENT Variables

fix variable name

---

README.md
package.json
src/index.ts
src/register.ts
src/typeDefinitions/default.types.d.ts
src/utils/registerCommands.ts

We are using itty-router, a lightweight router developed for Cloudflare workers.
Defined a route for get on `/` 
Configured it to return 404 in the case of any route apart from `get('/')`

[DRAFT] Feature/add routing

---

.github/workflows/register-commands-production.yaml

Add a workflow file that deploys the code and registers commands on the code getting merged to the main.

Add workflow to maintain continuous deployment on production

---

.github/workflows/register-commands-production.yaml
src/constants/errors.ts
src/constants/responses.ts
src/index.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/JsonResponse.ts
src/utils/verifyBot.ts

Create files that can interact with ping requests.
I have created a method to verify the bot to set up interaction URLs.
The function verifies if the request we received is a valid discord request.

Add verify bot to verify requests from discord to cfw

---

src/constants/responses.ts
src/controllers/baseHandler.ts
src/controllers/commandNotFound.ts
src/controllers/helloCommand.ts
src/index.ts
src/typeDefinitions/default.types.d.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/discordResponse.ts
src/utils/getCommandName.ts
src/utils/lowerCaseMessageCommand.ts
src/utils/verifyBot.ts

Added a base handler that checks for commands in messages and calls its respective handler.

add handler for hello command

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/commandNotFound.ts
src/controllers/helloCommand.ts
src/controllers/verifyCommand.ts
src/index.ts
src/register.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/discordResponse.ts
src/utils/sendDiscordDm.ts

This PR adds a verify command to our bot which sends a direct message to the user.
Currently, the message is just hello the actual link with the token will come up in the consecutive PRs.
To test out the PR in action please join my server: https://discord.gg/tRQrgm7D
and send the `/hello` and `/verify` commands.

add verify command

---

package-lock.json
src/constants/urls.ts
src/controllers/verifyCommand.ts
src/utils/generateUniqueToken.ts
src/utils/sendDiscordDm.ts

This PR generates a link to my site with a unique token for the user who sends `/verify`.
This Part just consists of generating a token. The token is not saved to the RDS backend yet.
Will add the part saving data in the RDS backend in future PRs.
To test out the PR in action please join my server: https://discord.gg/tRQrgm7D
and send the `/hello` and `/verify` commands.

add method to generate unique token and reply with link

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Closes #37
- Added production and staging name to the environments
- **Purpose :** To identify the environments by their name and use them for cases like `BASE_API_URL` for production and staging

Added environment name 

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml
src/constants/responses.ts
src/utils/updateNickname.ts

Created a utility function named `updateNickName` 
The function calls up on the `/guilds/DISCORD_GUILD_ID/members/discordId`
The function takes in 3 parameters:
- discord_Id: String
- nickname: String (desired nickname)
- env: Object which contains DISCORD_TOKEN, GUILD_ID
It is a patch call made to discord's API with a body of `{nick: nickname}`

add a utility which when called upon changes nickname

---

config/config.ts
src/constants/urls.ts
src/controllers/verifyCommand.ts
src/typeDefinitions/default.types.d.ts

since the staging of my site is set up thus I am adding a config to switch URLs based on environment

configure verification urls based on environment

---

CONTRIBUTING.md
src/constants/responses.ts
src/controllers/verifyCommand.ts
src/typeDefinitions/default.types.d.ts
src/utils/discordEphemeralResponse.ts
tests/unit/discordEphemeralResponse.test.ts

Following changes to be made live: 
- Able to get Epheremal message upon use of `/verify` command (By @samyakshah3008 ) 
Approved PR to dev branch: #51 
- Updated Contributing guide (By @nashitshayan and @RitikJaiswal75)
Approved PR: #49

Sync dev to main

---

tests/unit/utils/discordEphemeralResponse.test.ts
tests/unit/utils/discordResponse.test.ts
tests/unit/utils/getCommandName.test.ts
tests/unit/utils/getMembersInServer.test.ts
tests/unit/utils/guildRole.test.ts
tests/unit/utils/lowerCaseMessageCommands.test.ts

keep tests for utils in utils folder.

refactor folder structure

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/mentionEachUser.ts
src/register.ts
src/typeDefinitions/discordMessage.types.d.ts
src/typeDefinitions/filterUsersByRole.d.ts
src/typeDefinitions/filterUsersByRole.types.d.ts
src/typeDefinitions/register.types.d.ts
src/utils/checkDisplayType.ts
src/utils/filterUsersByRole.ts
tests/unit/handlers/mentionEachUser.test.ts

- This PR handles the series implementation i.e., users with mentioned roles in the command are tagged in a single message 
- the next iteration for this PR will add support for list which means all users will be tagged in a new message respectively 
[Ticket](https://github.com/Real-Dev-Squad/discord-slash-commands/issues/68)
Input: 👇
output:👇

feat: mention each command with series support

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/mentionEachUser.ts
src/utils/checkDisplayType.ts
tests/fixtures/fixture.ts
tests/unit/handlers/mentionEachUser.test.ts

- Fixes the structure of the existing command 
- rework on test 
new structure of the command 
Ticket: https://github.com/Real-Dev-Squad/discord-slash-commands/issues/75
I get the test coverage is low will increase that in another PR

feat: rework on existing mention-each command

---

package-lock.json
package.json

update packages and add scripts to help developers

---

config/config.ts
src/constants/urls.ts

add proper url and manage config

---

CONTRIBUTING.md

Issue : (#105)
- Updated the required steps necessary to set up discord-slash and rds-backend with discord
close(#105)

fix contribution.md

---

CONTRIBUTING.md
src/constants/commands.ts
src/constants/nicknameAffixes.ts
src/constants/responses.ts
src/controllers/baseHandler.ts
src/index.ts
src/register.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/removeListening.ts
tests/unit/utils/removeListening.test.ts

PR's going in:
- #104 
- #110 
**Feature**  : https://github.com/Real-Dev-Squad/discord-slash-commands/issues/109
**Staging Video** 
https://github.com/Real-Dev-Squad/discord-slash-commands/assets/61110378/21284e0c-33a6-4335-8b03-bffd8a5625f3

Dev to main sync

---

src/register.ts

Removed listening from register because the users which does'nt have nickname in their database, their nickname is becoming null.

removed /listening from register for now

---

src/index.ts
wrangler.toml

this is regarding #131 
Also the scheduled duration is set to 12 hours in this PR.

Making Auto fetch Overdue task live

---

src/utils/formatTask.ts
tests/fixtures/tasks.ts
tests/unit/utils/formatTask.test.ts

FIX: fix text format of task command response

---

src/handlers/scheduledEventHandler.ts
src/utils/getDiscordIds.ts
src/utils/taskOverDueDiscordMembers.ts
tests/unit/utils/getDiscordIds.test.ts
tests/unit/utils/taskOverDueDiscordMembers.test.ts

fixing auto over due fetch not working on prod

Fixing auto fetch over due tasks

---

src/constants/urls.ts

Date: 02-12-23
Developer Name: @prakashchoudhary07 
----
Change tracking channel id to tracking-updates channel id
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models must be updated._
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._
-   [x] Yes
-   [ ] No
_Confirm whether the changes have been tested locally during development._
-   [ ] Yes
-   [x] No
_Indicate whether the changes have been tested in the staging environment._
-   [ ] Yes
-   [x] No
_Specify if the changes are currently under a feature …

Change tracking channel id, to tracking-updates channel it

---

src/index.ts

Date: 16 December 2023
----
Removes bot auth for POST /roles
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._
-   [x] Yes
-   [ ] No
_Confirm whether the changes have been tested locally during development._
-   [x] Yes
-   [ ] No
_Indicate whether the changes have been tested in the staging environment._
-   [x] Yes
-   [ ] No
_Specify if the changes are currently under a feature flag._
**Database …

Removes bot auth for POST /roles

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Date: 17 December 2023
----
Github actions fails with node version 18.9. This PR downgrades that
https://github.com/TypeStrong/ts-node/issues/2094
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._
-   [ ] Yes
-   [x] No
_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._
-   [x] Yes
-   [ ] No
_Confirm whether the changes have been tested locally during development._
-   [x] Yes
-   [ ] No
_Indicate whether the changes have been tested in the staging environment._
-   [x] Yes …

Downgrade node version in actions runner

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Date: 17 December 2023
----
Fix indentation in GitHub workflows
- #173  
I have tested the workflow in forked repo. Please check it out if required: 
https://github.com/Ajeyakrishna-k/discord-slash-commands/blob/develop/.github/workflows/register-commands-staging.yaml

Fix indentation in GitHub workflows

---

src/constants/responses.ts
src/controllers/getMembersInServer.ts
src/utils/verifyAuthToken.ts
tests/unit/utils/verifyToken.test.ts

Date: 21 Thursday 2023
----
Fixes authentication 
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No

Fix authentication 

---

src/utils/verifyAuthToken.ts
tests/unit/utils/verifyToken.test.ts

Date: 10 Jan 2024
----
Adds a function to verify cron jobs auth token
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No

Adds a function to verify cron jobs auth token

---

src/controllers/guildRoleHandler.ts
tests/fixtures/fixture.ts
tests/unit/handlers/guildRoleHandler.test.ts

Reverts Real-Dev-Squad/discord-slash-commands#182

Revert "Changes the function to verify cron auth token"

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Date: 26/02/2024
Developer Name: @lakshayman 
---
https://github.com/Real-Dev-Squad/identity-service/issues/177
I changed the GitHub workflow to set the IDENTITY_SERVICE_PUBLIC_KEY from GitHub secrets to PRODUCTION and STAGING.

Set IDENTITY_SERVICE_PUBLIC_KEY environment while deploying

---

src/controllers/baseHandler.ts
src/controllers/verifyCommand.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/sendUserDiscordData.ts
tests/fixtures/fixture.ts
tests/unit/handlers/verifyCommand.test.ts

Date: 28 March 2024
Developer Name: Joy Gupta
---
- [Phase 2](https://github.com/Real-Dev-Squad/website-backend/issues/1974)
- https://docs.google.com/document/d/1kEA80FHwheR2cPlbWzleHoMzgWB0J4WeMUNe7RlApL4/edit
- https://github.com/Real-Dev-Squad/website-my/pull/588
- https://github.com/Real-Dev-Squad/website-backend/pull/1990
From this PR we are now sending discordJoinedAt field along with other info which later on gets saved in external-account collection.
NA
</details>

Feat : Added discordJoinedAt key

---

src/controllers/baseHandler.ts
src/controllers/verifyCommand.ts
src/typeDefinitions/discordMessage.types.d.ts
src/utils/sendUserDiscordData.ts
tests/fixtures/fixture.ts
tests/unit/handlers/verifyCommand.test.ts

Date: 11 April 2024
Developer Name: Joy Gupta
---
- [Phase 2](https://github.com/Real-Dev-Squad/website-backend/issues/1974)
- https://docs.google.com/document/d/1kEA80FHwheR2cPlbWzleHoMzgWB0J4WeMUNe7RlApL4/edit
- https://github.com/Real-Dev-Squad/website-my/pull/592
- https://github.com/Real-Dev-Squad/website-backend/pull/2008
From this PR we are now sending discordJoinedAt field along with other info which later on gets saved in external-account collection.
https://github.com/Real-Dev-Squad/website-my/assets/56365512/56302c49-d618-456c-86bd-8895dd71c6b4

Dev to Main Sync PR

---

src/controllers/taskUpdatesHandler.ts
src/index.ts
src/typeDefinitions/taskUpdate.d.ts
src/utils/sendTaskUpdates.ts
tests/unit/handlers/taskUpdateHandler.test.ts
tests/unit/utils/sendTasksUpdates.test.ts

Date: 2 April. 2024
Developer Name: Tejas
---
Developing an API that sends the updates of tasks in the RDS discord channel whenever the user updates his/her progress.
changes made in PR are firstly creating a controller that authorizes if the request is only coming from the backend of RDS  and then passing it to the util function which sends an update message on the tracking channel if the bot is authorized then only.
<details>
https://github.com/Real-Dev-Squad/discord-slash-commands/assets/98630752/7ccfa065-dcea-4614-bc61-8c493b77bda1
</details>
</details>

feat: add task update handler and util

---

src/utils/guildRole.ts

Date: 17 Aug 2024
Developer Name:  Joy Gupta
---
- https://github.com/Real-Dev-Squad/discord-slash-commands/issues/230
As there is no other way to add a delay in callbacks provided to ctx.waitUntil, faking a promise is the only way left

Chore : Added a delay in mention-each command (#231)

---

src/controllers/taskUpdatesHandler.ts
src/typeDefinitions/taskUpdate.d.ts
src/utils/sendTaskUpdates.ts
tests/unit/handlers/taskUpdateHandler.test.ts
tests/unit/utils/sendTasksUpdates.test.ts

Date: 16 Aug 2024
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-status/issues/1218
This Pr fixes undefined passed down in message in the tracking-update channel during the standup update 
<details>
[screen-capture (4).webm](https://github.com/user-attachments/assets/48cc6318-5942-4a46-82be-85890759809f)
</details>
<details>
</details>

Fixed passing of undefined in tracking update channel.

---

CONTRIBUTING.md

Date: 24 Aug 2024
Developer Name: Kavya Rishi
Made changes to the Bot Permission part in the Contributing.md

added changes to the Bot Permission part inside Contributing.md

---

.github/workflows/register-commands-staging.yaml

Added RDS_SERVERLESS_PUBLIC_KEY in register-commands-staging action
---
Added RDS_SERVERLESS_PUBLIC_KEY in actions
<details>
</details>
<details>
</details>

Added RDS_SERVERLESS_PUBLIC_KEY, to deploy on Cloudflare

---

src/index.ts

Debugging why tracking updates won't show up

Env issues debug index.ts

---

src/controllers/groupInvite.ts

Date: 05/10/24
Developer Name: @pallabez 
---
- Use encoded group name when converting to url
<details>
</details>
<details>
</details>

use encoded group name in group invite command

---

src/utils/awsAccess.ts
tests/unit/handlers/grantAwsAccessCommand.test.ts

Date: 
---
<details>
</details>
<details>
</details>

Grant aws access - test cases

---

package-lock.json
package.json

Date: 
---
<details>
</details>
<details>
</details>

Grant aws access

---

src/constants/commands.ts
src/controllers/mentionEachUser.ts
src/typeDefinitions/filterUsersByRole.d.ts
tests/unit/handlers/mentionEachUser.test.ts

Reverts Real-Dev-Squad/discord-slash-commands#275

Revert "remove feature flag from mention each user command"

---

package-lock.json

Date: 
---
<details>
</details>
<details>
</details>

correcting package.json file

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Date: 17th Nov
Developer Name:  Vikhyat
---
Relates to https://github.com/Real-Dev-Squad/discord-slash-commands/pull/276
<details>
</details>
<details>
</details>

Added the ENVs into the CI file

---

src/constants/commands.ts
src/controllers/onboardingExtensionCommand.ts
src/utils/onboardingExtension.ts
tests/unit/handlers/onboardingExtension.test.ts
tests/unit/utils/onboardingExtension.test.ts

Date: 23 Feb 2025
Developer Name: @mbramani
---
-  Closes https://github.com/Real-Dev-Squad/website-backend/issues/2376
- Removed feature flag for the following onboarding extension request features:
- Discord command `/onboarding-extension`  
<details>
https://github.com/user-attachments/assets/a1bc905f-96bd-4a5d-8c3d-10c2578def82
</details>
<details>
</details>

chore: remove feature flag onboarding extension command

---

.github/workflows/register-commands-production.yaml

Date: 
---
<details>
</details>
<details>
</details>

wrangler@v3 Update register-commands-production.yaml

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Needs to be fixed later - https://github.com/Real-Dev-Squad/discord-slash-commands/issues/304
Date: 
---
<details>
</details>
<details>
</details>

Fix deployments by using specific version of wrangler
