config/config.ts
src/constants/urls.ts
src/typeDefinitions/default.types.d.ts
tests/fixtures/config.ts
tests/unit/config/config.test.ts

Closes #39
- Created a function which switches the environment properties like BASE_API urls according to the environment being used.
- The environments currently supported are production, staging and development (also, default)   
- Written tests for the created function

Environment setup

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml

Please add the cloudflare account id before merging
Add CF account id to GitHub workflows.
Reason, We want to give minimum permission to cloudflare workers

add account-id

---

src/constants/responses.ts
src/controllers/changeNickname.ts
src/index.ts
src/utils/updateNickname.ts
tests/unit/utils/updateNickname.test.ts

create an endpoint that when hit changes the user's server nickname as per the RDS backend.
endpoint Method: `PATCH`
Headers: `JWT` signed with `BOT_PUBLIC_KEY` stored in the RDS backend
body: 
```json
{
id: <Discord id of the user>,
username: <RDS Username>
}
```
endpoint URL: `Cloudflare handler link`
path: `/name/update`
When the endpoint is hit with the above-mentioned attributes the server nickname of the user will be changed to the username passed in the request body.
The authorization header includes jwt which is verified to check if the request is from valid source.
Edge Cases
- User may change their server names after the patch request
- `solution`: stop allowing users to change nicknames in the server. Make sure only bot is able to do that.

Add a patch URL to change nickname

---

src/constants/responses.ts
src/controllers/guildRoleHandler.ts
src/index.ts
src/typeDefinitions/role.types.d.ts
src/utils/guildRole.ts
tests/fixtures/fixture.ts
tests/unit/handlers/guildRoleHandler.test.ts
tests/unit/utils/guildRole.test.ts

There was no API to get the role_id of roles in the server and role_ids were hard coded.
This PR adds the below APIs 
1:  GET `/roles`: Fetches all role IDs and names.
2:  GET `/roles/:roleName`: Retrieves role details (role_id and role_name) based on the provided role name.
These changes improve the system's ability to handle role-related operations and enhance the overall role-management experience.
N.A
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    
------------------------------|---------|----------|---------|---------|----------------------
All files                     |   83.33 |    86.36 |   89.28 |   82.87 |                 
responses.ts                |     100 |      100 |     100 |     100 |                    
guildRoleHandler.ts …

[Feature] Add APIs for fetching role information

---

src/constants/responses.ts
src/controllers/verifyCommand.ts

Description
after using /verify command, the reply message is showing just a link.
Ticket : https://github.com/Real-Dev-Squad/discord-slash-commands/issues/85
Adding TestCases of /verify feature : https://github.com/Real-Dev-Squad/discord-slash-commands/pull/90 :  **inprogress**

Raising different PR for /verify string

---

src/constants/responses.ts
src/controllers/guildRoleHandler.ts
src/controllers/verifyCommand.ts
src/index.ts
src/typeDefinitions/role.types.d.ts
src/utils/guildRole.ts
tests/fixtures/fixture.ts
tests/unit/handlers/guildRoleHandler.test.ts
tests/unit/utils/guildRole.test.ts

* adding tests for roles endpoint
* Feature: Create Discord API Endpoint to Remove Role from User (#82)
* add an api endpoint to relete role on discord
* revert commits to urls
* add test for remove guild role api
* remove unwanted changes
* add proper response headers
* adding tests for roles endpoint
* [Feature] Add APIs for fetching role information
* removing unnecessary constants
* Adding headers in response objects
* Adding extra try blocks in utils to handle errors
* Throwing errors when something goes wrong
* moving test constants to fixtures
* changing error type thrown on bad request
* Using roles url of discord to get roles details
* Raising different PR for /verify string (#94)
* raising different PR for /verify string
* resolved the comment
* fix lint issue
* fix lint issue …

Main to dev sync (#96)

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/userCommand.ts
src/register.ts
src/typeDefinitions/rdsUser.ts
src/utils/formatUserDetails.ts
tests/unit/utils/formatUserDetails.test.ts
tests/unit/utils/getUserDetails.test.ts

- This pull request introduces a new discord slash command **/user** which takes as an argument username and provides details of that user.
- Issue Ticket :  https://github.com/Real-Dev-Squad/discord-slash-commands/issues/106
- When this command is executed, it returns the following details of the user :
```md
**Full Name :** Jyotsna Mehta
**RDS Discord Joined At :** 31/05/2023 18:17:08
**State :** IDLE
```

/user command that gives details of a user

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/notifyCommand.ts
src/register.ts
src/utils/fetchRdsData.ts

**Pull Request Description:**
In this pull request, we are separating the `/notify` command into two distinct commands to provide more specific notifications to users.
1. `/notify-overdue`: This command is designed to notify users about overdue tasks.
**Options:**
- `Already Overdue`: This option will display a list of users with tasks that are already overdue.
- `In 1 Day`: This option will show the list of users whose tasks will become overdue in 1 day.
- `In 2 Days`: This option will show the list of users whose tasks will become overdue in 2 days.
2. `/notify-onboarding`: This command is intended to notify users about their onboarding status.
**Options:**
- `All Onboarding`: This option will display a list of users who are currently in the onboarding process.
- `> 7 Days`: This option …

REFACTOR: Separate /notify command

---

src/utils/formatUserDetails.ts
tests/unit/utils/formatUserDetails.test.ts

**What is change?**
- fix the alignment of `/user` response.
**Before: **
**After: **
**Test coverage: **

Fix /user response alignment 

---

src/controllers/userCommand.ts
src/utils/formatUserDetails.ts
tests/fixtures/user.ts
tests/unit/utils/formatUserDetails.test.ts

- https://github.com/Real-Dev-Squad/discord-slash-commands/issues/147
- This pull request introduces improvements to the handling of user details formatting in the `formatUserDetails` function and addresses the scenario where `discordJoinedAt` is undefined when we use the **/user** command.
- **userCommand.ts :** In the userCommand function, it is updated to return an appropriate response when the user details cannot be found.
- **formatUserDetails.ts :** In the formatUserDetails and convertTimeStamp functions, I've added enhanced handling for discordJoinedAt to ensure the user details are correctly formatted even when discordJoinedAt is undefined.
- **tests/fixtures/users.ts :** I've introduced a new fixture userWithoutDiscordJoinedAt representing a user without discordJoinedAt data.
- …

Fix Prod issues on /user command

---

src/utils/batchDiscordRequests.ts
src/utils/timeUtils.ts
tests/unit/utils/batchDiscordRequests.test.ts

Date: 8th December 2023
----
- #168
Discord provides rate limit headers like rate limit remaining and time after which rate limit resets, this can be used to schedule request to avoid being rate limited. This PR adds a generic method which can be used to request and schedule any discord end point which provides rate limit headers
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No

Adds a util function to schedule and execute discord requests according to its rate limits

---

src/constants/responses.ts
src/controllers/getMembersInServer.ts
src/utils/verifyAuthToken.ts
tests/unit/utils/verifyToken.test.ts

Date: 25 Dec 2023
----
- #179 
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No

Dev to main sync

---

src/utils/formatTask.ts
tests/unit/utils/formatTask.test.ts

Closes: https://github.com/Real-Dev-Squad/discord-slash-commands/issues/183
Change the response of `/task` command depending on `in-progress` task of user and write test for same.
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
Before :-
After :-

Fix response of /task command

---

src/controllers/changeNickname.ts
src/controllers/generateDiscordInvite.ts
src/controllers/guildRoleHandler.ts
src/utils/createDiscordHeaders.ts
src/utils/generateDiscordInvite.ts
src/utils/guildRole.ts
src/utils/updateNickname.ts
tests/unit/handlers/generateDiscordInvite.test.ts
tests/unit/utils/createDiscordHeaders.test.ts
tests/unit/utils/generateDiscordInvite.test.ts
tests/unit/utils/guildRole.test.ts
tests/unit/utils/updateNickname.test.ts

Date: 13-Jan-23
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/discord-slash-commands/issues/167
This PR enables it to pass reason in audit logs
Without supplying header the header is not passed down to the discord.
[screen-capture.webm](https://github.com/Real-Dev-Squad/discord-slash-commands/assets/68867418/9a8329e6-af6d-4c2d-a46a-2d15efc65180)
-When supplying header the header is passed down to the discord.
[screen-capture.webm](https://github.com/Real-Dev-Squad/discord-slash-commands/assets/68867418/52216308-9ca2-4eea-93aa-aba4946fb39f)

Added the header to passed down the API

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/mentionEachUser.ts
src/index.ts
src/typeDefinitions/discordMessage.types.d.ts
src/typeDefinitions/filterUsersByRole.d.ts
src/utils/batchDiscordRequests.ts
src/utils/guildRole.ts
src/utils/sleep.ts
tests/fixtures/fixture.ts
tests/unit/handlers/mentionEachUser.test.ts
tests/unit/utils/guildRole.test.ts
tests/unit/utils/sleep.test.ts

Date: 8 March 2024
Developer Name: Joy Gupta
---
- https://github.com/Real-Dev-Squad/discord-slash-commands/issues/188
This PR contains updated mention-each functionality. And also updated a field in some of the existing test cases.
In the images/video below you will see that is says found 3 users but then end up tagging so many users. This is because I am multiplying the matched users to test it out.
For failing use case
https://github.com/Real-Dev-Squad/discord-slash-commands/assets/56365512/18939c54-f72b-45a5-8fc6-30d95ad4f7bf
<section></section>
Video playback speed is 2x
https://github.com/Real-Dev-Squad/discord-slash-commands/assets/56365512/a45b3c2b-8bc1-46b6-aecd-31253e9add81
Tested it for 300 Users
<section>
<section>
<section>
</section>

Feat : Updated mention each flow

---

src/constants/responses.ts
src/controllers/taskUpdatesHandler.ts
src/typeDefinitions/taskUpdate.d.ts
src/utils/sendTaskUpdates.ts
tests/unit/handlers/taskUpdateHandler.test.ts
tests/unit/utils/sendTasksUpdates.test.ts

Date: 1 May, 2024
Developer Name: Tejas
---
#225 
This PR update  adds **taskTitle** field to the existing API which sends task updates on RDS discord's tacking-updates channel, now we want to modify the message that should have an hyperlink to the task.
</details>

add taskTitle field to /task/update API

---

src/utils/guildRole.ts

Date: 8 Aug 2024
Developer Name: @joyguptaa 
---
- #230 
This PR contains a fix that will add a delay before it starts tagging users 
Just for testing purpose, I am duplicating users. In actual those are 3 users only.
https://github.com/user-attachments/assets/0df67bd0-a042-407b-8fba-d6eb156f3b1c

Bug fix/mention each order

---

src/controllers/taskUpdatesHandler.ts
src/typeDefinitions/taskUpdate.d.ts
src/utils/guildRole.ts
src/utils/sendTaskUpdates.ts
tests/unit/handlers/taskUpdateHandler.test.ts
tests/unit/utils/sendTasksUpdates.test.ts

Date: 23 Aug 2024
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/discord-slash-commands/pull/232
https://github.com/Real-Dev-Squad/website-status/issues/1218
This PR fix undefined getting passed to the standup while standup update
<details>
Staging proof #232 
</details>

Dev to main sync PR

---

src/constants/commands.ts
src/controllers/baseHandler.ts
src/controllers/userCommand.ts
src/utils/formatUserDetails.ts
tests/fixtures/user.ts
tests/unit/utils/formatUserDetails.test.ts

Date:  09/09/24
Developer Name: Prashant Peeyush
---
- Closes #243 
**userId** & **userName**  will also be displayed along with other details when `/user` command is run on discord
<details>
[screen-capture (4).webm](https://github.com/user-attachments/assets/aa924976-2c68-4054-81e8-cf7ff4bbca44)
</details>
<details>
</details>

Added username & userId to /user command

---

src/controllers/baseHandler.ts
src/register.ts

Date: 9th october 2024 
Developer Name: yash raj
---
- N/A
- comment the code for `/remove` command to prevent nonsuper users from calling the command.
- this change should be reverted once a superuser check is added in `kickEachUser` function.

remove the `/remove` command

---

src/constants/commands.ts
src/controllers/mentionEachUser.ts
src/typeDefinitions/filterUsersByRole.d.ts
tests/unit/handlers/mentionEachUser.test.ts

Date: 17-10-2024
Developer Name: Rishi Chaubey
---
Removed the feature flag from mentionEach command as the flag is not required
<details>
</details>
<details>
</details>
this is the screen recording without feature flag
https://github.com/user-attachments/assets/8af999e3-94c4-4389-a028-e59a8a5f70ef
this is the screen recording when there was feature flag before
https://github.com/user-attachments/assets/ce30aab0-d1ce-4114-97aa-f7292d098d1e

remove feature flag from mention each user command

---

README.md

Date: 22-12-24
Developer Name: Vikhyat
---
Added the AWS env variable in the readme file of the discord slash command
<details>
</details>
<details>
</details>

Added AWS env variable in the readme file

---

src/constants/commands.ts
src/constants/responses.ts
src/controllers/baseHandler.ts
src/controllers/onboardingExtensionCommand.ts
src/register.ts
src/typeDefinitions/rdsUser.ts
src/utils/onboardingExtension.ts
src/utils/sendReplyInDiscordChannel.ts
tests/fixtures/fixture.ts
tests/unit/handlers/onboardingExtension.test.ts
tests/unit/utils/onboardingExtension.test.ts
tests/unit/utils/sendReplyInDiscordChannel.test.ts

Date: 20 Dec, 2024
Developer Name: @pankajjs 
---
- Closes https://github.com/Real-Dev-Squad/website-backend/issues/2187
- This PR creates a discord slash command `/onboarding-extension <number-of-days> <reason> <username>` which interacts with website backend and creates an onboarding extension request for onboarding user.
- This command can only be executed for onboarding user.
- Only the onboarding users themselves or the super users can execute this command.
<details>
<summary>Working Videos</summary>
- When super-users make request for onboarding users and do not pass username
https://github.com/user-attachments/assets/fe7bdc50-ef81-4c57-89cb-a44cb6306eaf
- When super-users make request for onboarding users
https://github.com/user-attachments/assets/b8098f1c-7f1a-4c3a-85be-ebd794cc408 …

feat: Add onboarding extension command to create an onboarding extension request

---

.github/workflows/register-commands-production.yaml
.github/workflows/register-commands-staging.yaml
package-lock.json
package.json
tests/fixtures/fixture.ts
tests/unit/handlers/grantAwsAccessCommand.test.ts
wrangler.toml

Date: 4 May 2025
Developer Name: @AnujChhikara 
---
- #304 
- Upgraded `wrangler` to v4 
- Updated all mocks in unit tests to include the required `props` field introduced in v4 types
- Updated CI workflow to use the Wrangler version defined in `package.json` instead of a hardcoded version.
<details>
</details>
<details>
</details>

chore: upgrade wrangler to v4 
